### ISSUE TITLE
Duplicate plugin

### ISSUE THREAD

**Issue by pfefferle** [petermolnar/wp-featured2rss#1]
Perhaps this will save you some time: https://wordpress.org/plugins/add-featured-image-to-rss-feed/

**Comment by pfefferle** [comment]
Oh, too late ;)

**Comment by petermolnar** [comment]
Hmmm, I missed that :D
I've had this in my theme setup for a while, just splitted into a plugin; thank you anyway.

**Comment by petermolnar** [comment]
Also, that one adds the thumbnail as enclosure, I wanted something that detects the largest available resized image and attaches that.

**Comment by pfefferle** [comment]
oh nice! will you release it on the WordPress directory?

**Comment by petermolnar** [comment]
No, not now. The WP plugin directory is a mess, and I'm a little unhappy with it right now; eg. they have a PHP lint hook for version 5.4; anything that uses things from PHP 5.5, 5.6 or 7 are usually rejected with parse error.
